spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/seller_db
    username: dco_user
    password: dco_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  grpc:
    server:
      port: 9090

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml