server:
  port: 8081

debug: true

spring:
#  profiles:
#    #    для локальной работы,чтобы не лезть в гошку на сервис
#    active: local

  datasource:
    url: jdbc:postgresql://localhost:5433/seller_db
    username: dco_user
    password: dco_password
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 10000
    logging:
      level:
        org.hibernate: DEBUG
        org.springframework.jdbc: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

#  grpc:
#    server:
#      port: 9090

  liquibase:
    enabled: false