spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/seller_db
    username: dco_user
    password: dco_password
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 10000

    logging:
      level:
        org.hibernate: DEBUG
        org.springframework.jdbc: DEBUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  grpc:
    server:
      port: 9090

  liquibase:
    enabled: false