version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: dco-postgres
    environment:
      POSTGRES_USER: dco_user
      POSTGRES_PASSWORD: dco_password
      POSTGRES_DB: seller_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - dco-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dco_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kotlin-seller-service:
    image: eclipse-temurin:17-jdk # JDK 17, чтобы запускать jar
    container_name: seller-service
    working_dir: /app
    volumes:
      - ../build/libs:/app
    command: ["java", "-jar", "registration-service-0.0.1-SNAPSHOT.jar"] # название jar поправь!
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seller_db
      SPRING_DATASOURCE_USERNAME: dco_user
      SPRING_DATASOURCE_PASSWORD: dco_password
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - dco-network

volumes:
  postgres_data:

networks:
  dco-network:
    driver: bridge
